export const prospectInfo = [
    {firstName: 'Leanne',
     lastName: 'Graham',
     prospectId: "1",
     checked: false},
     {firstName: 'Ervin',
     lastName: 'Howell',
     prospectId: "2",
     checked: false},
     {firstName: 'Clementine',
     lastName: 'Bauch',
     prospectId: "3",
     checked: false},
     {firstName: 'Patricia',
     lastName: 'Lebsack',
     prospectId: "4",
     checked: false},
     {firstName: 'Chelsey',
     lastName: 'Dietrich',
     prospectId: "5",
     checked: false},
     {firstName: 'Glenna',
     lastName: 'Reichert',
     prospectId: "6",
     checked: false}
  ]